POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RhYWphMSIsImlkIjoiNjY5OTI4NDk3MTlhODY2YzkyYWNiZTEyIiwiaWF0IjoxNzIxODE1MTQ3LCJleHAiOjE3MjE4MTg3NDd9.iUcIeGiCwRc4dSE3gAyJy8bnYpHaQMwYvv8D0e7sIRk


{
  "title": "Type wars",
  "author": "Robert C. Martin",
  "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
  "likes": 2
}

